#!/bin/bash

jupyter serverextension enable --py nbgitpuller --sys-prefix
jt -t grade3 -f firacode -T -N -kl -cellw 90%  -cursc g

# go ahead and build the XSPEC models
python -c "from astromodel.xspec import *"
